module.exports = {
    events: [{
        name: 'Bridal Portraits',
        link: 'bridal',
        assists: [
            'Alicia',
            'Andrew',
            'Christy',
            'Corrine',
            'Courtney',
            'Dan G',
            'Dan F',
            'Dawn',
            'Denise S',
            'Earl',
            'Emily',
            'Evelyn',
            'George',
            'Jaime',
            'Jennifer M',
            'John',
            'Joselyn',
            'Lindsay',
            'Mercedes',
            'Michael',
            'Uma',
            'Jorge',
            'Stephanie B',
            'Tina'
        ]
    },{
        name: 'Family Portraits',
        link: 'family',
        assists:  [
            'Alicia',
            'Andrew',
            'Christy',
            'Corrine',
            'Courtney',
            'Dan G',
            'Dan F',
            'Dawn',
            'Denise S',
            'Earl',
            'Eddie',
            'Emily',
            'Eric H',
            'Eric W',
            'Erica',
            'Evelyn',
            'George',
            'Howie',
            'J.R',
            'Jackson',
            'Jaime',
            'John',
            'Joselyn',
            'Lindsay',
            'Matt',
            'Mercedes',
            'Michael',
            'Mike',
            'Uma',
            'Jorge',
            'Stephanie B',
            'Tina'
        ]
    },{
        name: 'On-Location Studio',
        link: 'family',
        assists:  [
            'Alicia',
            'Andrew',
            'Cassie',
            'Christy',
            'Corrine',
            'Courtney',
            'Cyndi',
            'Dan G',
            'Dan F',
            'Dawn',
            'Denise B',
            'Denise S',
            'Diana',
            'Dio',
            'Earl',
            'Eddie',
            'Emily',
            'Eric H',
            'Eric W',
            'Erica',
            'Evelyn',
            'George',
            'Howie',
            'J.R',
            'Jackson',
            'Jaime',
            'Jamie Lynn',
            'Jennifer',
            'John',
            'Jon P',
            'Joselyn',
            'Kathryn',
            'Matt',
            'Mercedes',
            'Mike',
            'Uma',
            'Jorge',
            'Stephanie B',
            'Tina',
            'Trent',
            'Yeni'
        ]
    },{
        name: 'DPA/Group Photos',
        link: 'family',
        assists:  [
            'Andrew',
            'Christy',
            'Courtney',
            'Cyndi',
            'Dan G',
            'Dawn',
            'Denise B',
            'Denise S',
            'Dio',
            'Earl',
            'Eddie',
            'Emily',
            'Eric H',
            'Eric W',
            'George',
            'J.R',
            'Jackson',
            'Jaime',
            'John',
            'Joselyn',
            'Kathryn',
            'Matt',
            'Mercedes',
            'Mike',
            'Uma',
            'Stephanie B',
            'Trent'
        ]
    }]
}